Repository GemsForge/csharp-projects-beg, pull requests merged in 2024-09, with the labels that each got.

#4 tt(fix): #3 task tracker modifies tasks in Task List JSON file
  TaskTracker.Tests/TaskManagerTests.cs
  TaskTracker/data/TaskManager.cs
Labels: bug

#6 tt: #5 brand ASCII generated logo added to console
  TaskTracker/Brand Logo/Logo.cs
  TaskTracker/Program.cs
Labels: enhancement

#8 Add Task tracker CLI Project to Csharp projects
  README.md
  TaskTracker.Tests/TaskCLITests.cs
  TaskTracker.Tests/TaskManagerTests.cs
  TaskTracker.Tests/TaskRepositoryTests.cs
  TaskTracker.Tests/TaskServiceTests.cs
  TaskTracker.Tests/TaskTracker - Backup.Tests.csproj
  TaskTracker.Tests/TaskTracker.Tests.csproj
  TaskTracker.Tests/Usings.cs
  TaskTracker.Tests/test_tasks.json
  TaskTracker/Brand Logo/Logo.cs
  TaskTracker/Program.cs
  TaskTracker/TaskTracker.csproj
  TaskTracker/data/ITaskManager.cs
  TaskTracker/data/ITaskRepository.cs
  TaskTracker/data/TaskManager.cs
  TaskTracker/data/TaskRepository.cs
  TaskTracker/data/Tasks.json
  TaskTracker/dto/TaskDto.cs
  TaskTracker/model/Status.cs
  TaskTracker/model/StatusEnumConverter.cs
  TaskTracker/model/Task.cs
  TaskTracker/services/ITaskService.cs
  TaskTracker/services/TaskService.cs
  TaskTracker/ui/TaskCLI.cs
  csharp_projects.sln
Labels: enhancement

#9 Merge Fizz Buzz Game to main branch
  FizzBuzzGame.Tests/FizzBuzzArcadeTests.cs
  FizzBuzzGame.Tests/FizzBuzzDisplayTests.cs
  FizzBuzzGame.Tests/FizzBuzzGame.Tests.csproj
  FizzBuzzGame.Tests/FizzBuzzServiceTests.cs
  FizzBuzzGame.Tests/Usings.cs
  FizzBuzzGame/FizzBuzzGame.csproj
  FizzBuzzGame/Program.cs
  FizzBuzzGame/brandLogo/Logo.cs
  FizzBuzzGame/game/FizzBuzzArcade.cs
  FizzBuzzGame/game/FizzBuzzDisplay.cs
  FizzBuzzGame/game/IFizzBuzzDisplay.cs
  FizzBuzzGame/images/fizzbuzz_game_preview-v1-03Sep2024.png
  FizzBuzzGame/model/FizzBuzz.cs
  FizzBuzzGame/service/FizzBuzzService.cs
  FizzBuzzGame/service/IFizzBuzzService.cs
  README.md
  csharp_projects.sln
Labels: enhancement

#14 fb: add exit task to fizz buzz arcade #10
  FizzBuzzGame/game/FizzBuzzArcade.cs
Labels: enhancement

#16 fb: added score keeping for arcade #15
  FizzBuzzGame/game/FizzBuzzArcade.cs
  FizzBuzzGame/game/FizzBuzzDisplay.cs
  FizzBuzzGame/game/IFizzBuzzDisplay.cs
  FizzBuzzGame/service/FizzBuzzService.cs
  FizzBuzzGame/service/IFizzBuzzService.cs
Labels: enhancement

#19 17 create task tracker api and rename task tracker project to tasktrackercli
  CommonLibrary/CommonLibrary.csproj
  CommonLibrary/TaskTracker/data/ITaskManager.cs
  CommonLibrary/TaskTracker/data/ITaskRepository.cs
  CommonLibrary/TaskTracker/data/TaskManager.cs
  CommonLibrary/TaskTracker/data/TaskRepository.cs
  CommonLibrary/TaskTracker/data/Tasks.json
  CommonLibrary/TaskTracker/dto/TaskDto.cs
  CommonLibrary/TaskTracker/model/Status.cs
  CommonLibrary/TaskTracker/model/StatusEnumConverter.cs
  CommonLibrary/TaskTracker/model/Task.cs
  TaskTracker.Tests/TaskCLITests.cs
  TaskTracker.Tests/TaskManagerTests.cs
  TaskTracker.Tests/TaskRepositoryTests.cs
  TaskTracker.Tests/TaskServiceTests.cs
  TaskTracker.Tests/TaskTracker.Tests.csproj
  TaskTracker/Program.cs
  TaskTracker/TaskTrackerConsole.csproj
  TaskTracker/dto/TaskDto.cs
  TaskTracker/model/Status.cs
  TaskTracker/services/ITaskService.cs
  TaskTracker/services/TaskService.cs
  TaskTracker/ui/TaskCLI.cs
  TaskTrackerAPI/Controllers/TaskTrackerController.cs
  TaskTrackerAPI/Pages/Index.cshtml
  TaskTrackerAPI/Pages/Index.cshtml.cs
  TaskTrackerAPI/Program.cs
  TaskTrackerAPI/Properties/launchSettings.json
  TaskTrackerAPI/TaskTrackerAPI.csproj
  TaskTrackerAPI/appsettings.Development.json
  TaskTrackerAPI/appsettings.json
  csharp_projects.sln
Labels: enhancement

#22 21 create console user authentication and management system
  README.md
  SecureUserConsole/Program.cs
  SecureUserConsole/SecureUserConsole.csproj
  SecureUserConsole/data/IUserRepository.cs
  SecureUserConsole/data/UserRepository.cs
  SecureUserConsole/data/Users.json
  SecureUserConsole/dto/UserRegisterDto.cs
  SecureUserConsole/model/User.cs
  SecureUserConsole/service/IPasswordUtility.cs
  SecureUserConsole/service/IUserManager.cs
  SecureUserConsole/service/IUserService.cs
  SecureUserConsole/service/PasswordUtility.cs
  SecureUserConsole/service/UserManager.cs
  SecureUserConsole/service/UserService.cs
  SecureUserConsole/ui/UserCli.cs
  SecureUserConsole/ui/UserInputValidator.cs
  SecureUserConsoleTests/SecureUserConsoleTests.csproj
  SecureUserConsoleTests/service/PasswordUtilityTests.cs
  SecureUserConsoleTests/service/UserManagerTests.cs
  csharp_projects.sln
Labels: enhancement

#25 23 add password reset functionality to secure user manager
  SecureUserConsole/Program.cs
  SecureUserConsole/data/Users.json
  SecureUserConsole/service/IPasswordResetService.cs
  SecureUserConsole/service/PasswordResetService.cs
  SecureUserConsole/service/UserManager.cs
  SecureUserConsole/ui/UserCli.cs
  SecureUserConsoleTests/SecureUserConsole.Tests.csproj
  SecureUserConsoleTests/service/PasswordResetServiceTests.cs
  csharp_projects.sln
Labels: enhancement

#27 26 create web api for secure user manager
  SecureUserAPI/Controllers/AuthController.cs
  SecureUserAPI/Controllers/UserController.cs
  SecureUserAPI/DTO/LoginDto.cs
  SecureUserAPI/DTO/PasswordResetDto.cs
  SecureUserAPI/DTO/RegisterDto.cs
  SecureUserAPI/DTO/UpdateUserDto.cs
  SecureUserAPI/Mappers/IUserMapper.cs
  SecureUserAPI/Mappers/UserMapper.cs
  SecureUserAPI/Program.cs
  SecureUserAPI/Properties/launchSettings.json
  SecureUserAPI/SecureUserAPI.csproj
  SecureUserAPI/appsettings.Development.json
  SecureUserAPI/appsettings.json
  SecureUserConsole/Program.cs
  SecureUserConsole/SecureUserConsole.csproj
  SecureUserConsole/data/UserRepository.cs
  SecureUserConsole/data/Users.json
  SecureUserConsole/service/IUserManager.cs
  SecureUserConsole/service/UserManager.cs
  csharp_projects.sln
Labels: enhancement

#37 su(feat): #28 created master api project with initial setup and proje…
  GemConnectAPI/GemConnectAPI.csproj
  GemConnectAPI/Program.cs
  GemConnectAPI/Properties/launchSettings.json
  GemConnectAPI/appsettings.Development.json
  GemConnectAPI/appsettings.json
  csharp_projects.sln
Labels: enhancement

#40 32 integrate fizzbuzz game with master api
  FizzBuzzConsole/FizzBuzzConsole.csproj
  FizzBuzzConsole/Program.cs
  FizzBuzzConsole/data/FizzBuzz.json
  FizzBuzzConsole/data/FizzBuzzRepository.cs
  FizzBuzzConsole/data/IFizzBuzzRepository.cs
  FizzBuzzConsole/game/FizzBuzzArcade.cs
  FizzBuzzConsole/game/FizzBuzzDisplay.cs
  FizzBuzzConsole/manager/FizzBuzzManager.cs
  FizzBuzzConsole/manager/IFizzBuzzManager.cs
  FizzBuzzConsole/model/FizzBuzz.cs
  FizzBuzzConsole/model/FizzBuzzGameplay.cs
  FizzBuzzConsole/model/FizzBuzzGuess.cs
  FizzBuzzConsole/service/FizzBuzzService.cs
  FizzBuzzConsole/service/IFizzBuzzService.cs
  FizzBuzzGame.Tests/FizzBuzzServiceTests.cs
  GemConnectAPI/Controllers/FizzBuzz/FizzBuzzController.cs
  GemConnectAPI/DTO/FizzBuzzDto.cs
  GemConnectAPI/Extensions/ServiceRegistrationExtensions.cs
  GemConnectAPI/Extensions/SwaggerExtensions.cs
  GemConnectAPI/Program.cs
  GemConnectAPI/appsettings.json
Labels: enhancement

#41 gc(refactor): #30 renamed user and auth controllers to AdminControlle…
  GemConnectAPI/Controllers/SecureUser/AdminController.cs
  GemConnectAPI/Controllers/SecureUser/LoginController.cs
Labels: enhancement

#42 33 set up shared json database for all services
  CommonLibrary/CommonLibrary.csproj
  CommonLibrary/Data/GenericJsonRepository.cs
  CommonLibrary/Data/IGenericRepository.cs
  CommonLibrary/Data/SharedData.json
  FizzBuzzConsole/Program.cs
  FizzBuzzConsole/data/FizzBuzz.json
  FizzBuzzConsole/game/FizzBuzzArcade.cs
  FizzBuzzConsole/model/FizzBuzzGameplay.cs
  FizzBuzzConsole/service/FizzBuzzService.cs
  FizzBuzzConsole/service/IFizzBuzzService.cs
  GemConnectAPI/Controllers/FizzBuzz/FizzBuzzController.cs
  GemConnectAPI/Controllers/SecureUser/AdminController.cs
  GemConnectAPI/Controllers/SecureUser/AuthController.cs
  GemConnectAPI/Controllers/SecureUser/LoginController.cs
  GemConnectAPI/Controllers/TaskTracker/TaskTrackerController.cs
  GemConnectAPI/Extensions/ServiceRegistrationExtensions.cs
  GemConnectAPI/GemConnectAPI.csproj
  GemConnectAPI/Program.cs
  GemConnectAPI/Services/SecureUser/ApiUserManager.cs
  GemConnectAPI/appsettings.json
  SecureUserAPI/Controllers/AuthController.cs
  SecureUserAPI/Controllers/UserController.cs
  SecureUserAPI/Program.cs
  SecureUserConsole/Program.cs
  SecureUserConsole/data/Users.json
  SecureUserConsole/manager/IUserManager.cs
  SecureUserConsole/manager/UserManager.cs
  SecureUserConsole/model/User.cs
  SecureUserConsole/service/UserService.cs
  SecureUserConsole/ui/UserCli.cs
  SecureUserConsoleTests/service/UserManagerTests.cs
  TaskTracker.Tests/TaskCLITests.cs
  TaskTracker.Tests/TaskServiceTests.cs
  TaskTrackerAPI/Controllers/TaskTrackerController.cs
  TaskTrackerAPI/Pages/Index.cshtml.cs
  TaskTrackerAPI/Program.cs
  TaskTrackerConsole/Program.cs
  TaskTrackerConsole/Properties/launchSettings.json
  TaskTrackerConsole/manager/ITaskManager.cs
  TaskTrackerConsole/manager/TaskManager.cs
  TaskTrackerConsole/model/Task.cs
  TaskTrackerConsole/service/ITaskService.cs
  TaskTrackerConsole/service/TaskService.cs
  TaskTrackerConsole/ui/TaskCLI.cs
Labels: enhancement

#44 gc(cleanup): #43 removed api projects from solution
  csharp_projects.sln
Labels: enhancement

#46 gc(doc): #35 updated examples for the models to be displayed in the S…
  FizzBuzzConsole/model/FizzBuzzGameplay.cs
  GemConnectAPI/DTO/SecureUser/LoginDto.cs
  GemConnectAPI/DTO/SecureUser/PasswordResetDto.cs
  GemConnectAPI/DTO/SecureUser/RegisterDto.cs
  GemConnectAPI/DTO/SecureUser/UpdateUserDto.cs
  GemConnectAPI/DTO/TaskTracker/TaskDto.cs
  SecureUserConsole/model/User.cs
  TaskTrackerConsole/dto/TaskDto.cs
  TaskTrackerConsole/model/Task.cs
Labels: documentation
